export const BUTTON_TEXT = {
  EDIT: 'Edit',
  DUPLICATE: 'Duplicate',
  DELETE: 'Delete',
  HISTORY: 'History',
  CANCEL: 'Cancel',
  SAVE_AND_NEW: 'Save & Add New',
  CLONE: 'Clone',
  SAVE: 'Salveaza',
  COPY_TO_CLIPBOARD: 'Copy to clipboard',
  EXPORT: 'Export',
  REGISTER: 'Inregistrare',
  AUTH: 'Autentificare',
  RESET_PASSWORD: 'Reseteaza parola',
  LOGOUT: 'Log out',
}
